services:
  - type: web
    name: neropage
    runtime: node
    plan: starter
    buildCommand: npm install && npm run db:push -- --force && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: neropage-db
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: neropage-db
    plan: starter
    databaseName: neropage
    user: neropage
